#393 - highcharts ssr compatibility angular
highcharts/highcharts-angular pull request #394
Opened 2024-11-30 09:29 UTC by kai1992cool

#393 - highcharts ssr compatibility angular

The documentation should also be updated for the same. There is no if condition needed, it will simply work for SSR.

2024-12-06 10:00 UTC, karolkolodziej requested changes
Thank you for the update! 
Could you please change the documentation accordingly? 

Keep in mind that we are going to release a new version of this integration and this might not end up in the production.

2024-12-06 10:00 UTC, karolkolodziej commented on highcharts-angular/src/lib/highcharts-chart.component.ts
> +    private @Inject(PLATFORM_ID) platformId: Object,
```suggestion
    @Inject(PLATFORM_ID) private platformId: Object
```

2024-12-06 10:00 UTC, karolkolodziej commented on highcharts-angular/src/lib/highcharts-chart.component.ts
> +    this.ssrCompatible();
This won't work. You need to make it like this:

```ts
ngOnChanges(changes: SimpleChanges): void {
 if (this.ssrCompatible()) {
      return;
    }
...
```

[See in the demo.
](https://jsfiddle.net/BlackLabel/x35syfan/)

2024-12-06 13:54 UTC, PowerKiKi commented on highcharts-angular/src/lib/highcharts-chart.component.ts
> +import { isplatFormServer } from '@angular/common';
```suggestion
import { isPlatformServer } from '@angular/common';
```

2025-06-23 07:29 UTC, karolkolodziej commented
Closing due to inactivity.

2025-06-23 07:29 UTC, closed without merging